# Generated by Django 4.2.16 on 2024-11-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forename',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='surename',
            field=models.CharField(default='testsurname', max_length=50),
            preserve_default=False,
        ),
    ]
