# Generated by Django 4.2.16 on 2024-11-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_forename_user_surename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='forename',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surename',
        ),
    ]
