# Generated by Django 4.2.16 on 2025-01-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_researchfield_university_alter_user_institute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchfield',
            name='id',
        ),
        migrations.RemoveField(
            model_name='university',
            name='id',
        ),
        migrations.AlterField(
            model_name='researchfield',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
