# Generated by Django 4.2.16 on 2024-11-19 22:29

from django.db import migrations


class Migration(migrations.Migration):
    conversion_factors = {
        "Electricity consumption (kWh)": {"units": "kg CO2e", "value": 0.212},
        "Transmission & distribution (kg CO2e)": {"units": "kg CO2e", "value": 0.019},
        "Gas consumption (kWh)": {"units": "kg CO2e", "value": 0.183},
        "Water consumption (m3)": {"units": "kg CO2e", "value": 0.149},
        "Water treatment (m3)": {"units": "kg CO2e", "value": 0.272},
        "Air - Economy short-haul, to/from UK": {"units": "kg CO2e", "value": 0.151},
        "Air - Business short-haul, to/from UK": {"units": "kg CO2e", "value": 0.227},
        "Air - Economy long-haul, to/from UK": {"units": "kg CO2e", "value": 0.148},
        "Air - Business long-haul, to/from UK": {"units": "kg CO2e", "value": 0.429},
        "Air - Economy international, to/from non-UK": {"units": "kg CO2e", "value": 0.141},
        "Air - Business international, to/from non-UK": {"units": "kg CO2e", "value": 0.408},
        "Sea - Ferry": {"units": "kg CO2e", "value": 0.113},
        "Land - Car": {"units": "kg CO2e", "value": 0.168},
        "Land - Motorbike": {"units": "kg CO2e", "value": 0.114},
        "Land - Taxis": {"units": "kg CO2e", "value": 0.149},
        "Land - Local Bus": {"units": "kg CO2e", "value": 0.102},
        "Land - Coach": {"units": "kg CO2e", "value": 0.027},
        "Land - National rail": {"units": "kg CO2e", "value": 0.035},
        "Land - International rail": {"units": "kg CO2e", "value": 0.004},
        "Land - Light rail and tram": {"units": "kg CO2e", "value": 0.029},
        "Mixed recycling": {"units": "kg CO2e", "value": 21.294},
        "General waste": {"units": "kg CO2e", "value": 446.242},
        "Clinical waste": {"units": "kg CO2e", "value": 297.000},
        "Chemical waste": {"units": "kg CO2e", "value": 273.000},
        "Biological waste": {"units": "kg CO2e", "value": 1000.000},
        "WEEE mixed recycling": {"units": "kg CO2e", "value": 21.294},
    }

    data = {
        "General UofG data": [
            {
                "consumption_type": "electricity",
                "category": "Non-residential Electricity",
                "amount": 1447054,
                "unit": "kWh",
                "year": 2024,
                "notes": "",
            },
            {
                "consumption_type": "electricity",
                "category": "Residential Electricity",
                "amount": 59822627,
                "unit": "kWh",
                "year": 2024,
                "notes": "",
            },
            {
                "consumption_type": "gas",
                "category": "Non-residential Gas",
                "amount": 2377808,
                "unit": "kWh",
                "year": 2024,
                "notes": "",
            },
            {
                "consumption_type": "gas",
                "category": "Residential Gas",
                "amount": 91996054,
                "unit": "kWh",
                "year": 2024,
                "notes": "",
            },
            {
                "consumption_type": "electricity",
                "category": "Total Electricity Benchmark",
                "amount": 137.54,
                "unit": "kWh/m²",
                "year": 2024,
                "notes": "",
            },
            {
                "consumption_type": "gas",
                "category": "Total Gas Benchmark",
                "amount": 211.85,
                "unit": "kWh/m²",
                "year": 2024,
                "notes": "",
            },
        ],
        "Adjusted electricity and gas benchmark for UofG spaces": [
            {
                "consumption_type": "electricity",
                "category": "Academic Laboratory Benchmark",
                "amount": 207.99,
                "unit": "kWh/m²",
                "year": 2024,
                "notes": "",
            },
            {
                "consumption_type": "gas",
                "category": "Academic Laboratory Benchmark",
                "amount": 247.39,
                "unit": "kWh/m²",
                "year": 2024,
                "notes": "",
            },
            {
                "consumption_type": "electricity",
                "category": "Academic Office Benchmark",
                "amount": 108.47,
                "unit": "kWh/m²",
                "year": 2024,
                "notes": "",
            },
            {
                "consumption_type": "gas",
                "category": "Academic Office Benchmark",
                "amount": 170.85,
                "unit": "kWh/m²",
                "year": 2024,
                "notes": "",
            },
            {
                "consumption_type": "electricity",
                "category": "Admin Office Benchmark",
                "amount": 115.17,
                "unit": "kWh/m²",
                "year": 2024,
                "notes": "",
            },
            {
                "consumption_type": "gas",
                "category": "Admin Office Benchmark",
                "amount": 180.41,
                "unit": "kWh/m²",
                "year": 2024,
                "notes": "",
            },
        ],
        "Water Benchmark": [
            {
                "consumption_type": "water",
                "category": "Physical Sciences Laboratory",
                "amount": 1.7,
                "unit": "m³/m²",
                "year": 2024,
                "notes": "",
            },
            {
                "consumption_type": "water",
                "category": "Medical/Life Sciences Laboratory",
                "amount": 1.4,
                "unit": "m³/m²",
                "year": 2024,
                "notes": "",
            },
            {
                "consumption_type": "water",
                "category": "Engineering Laboratory",
                "amount": 1.7,
                "unit": "m³/m²",
                "year": 2024,
                "notes": "",
            },
            {
                "consumption_type": "water",
                "category": "Office/Admin Space",
                "amount": 1.0,
                "unit": "m³/m²",
                "year": 2024,
                "notes": "",
            },
        ],
    }



    def populate_conversion_factors():
        Person = apps.get_model("yourappname", "Person")
    dependencies = [
        ('accounts', '0003_remove_user_forename_remove_user_surename'),
    ]

    operations = [
    ]
