# Generated by Django 4.2.16 on 2024-11-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_benchmarkdata_conversionfactor_spacetypeentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fisrtname',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
    ]
