# Generated by Django 4.2.16 on 2024-11-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_fisrtname_user_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fisrtname',
            new_name='firstname',
        ),
    ]
