stages:
  - lint
  - build

lint-backend:
  stage: lint
  image: python:3.11-slim
  script:
    - pip install ruff
    - ruff check backend/

lint-frontend:
  stage: lint
  image: node:23
  script:
    - npm i eslint
    - node_modules/eslint/bin/eslint.js frontend/ 

build-job:
  stage: build
  image: node:23
  variables:
    VITE_BACKEND_URL: "https://sh14main-django2-1.onrender.com/"
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
    - build/