build-job:
  stage: build
  image: node:23
  variables:
    VITE_BACKEND_URL: "http://localhost:8000/"
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
    - build/