stages:
  - lint
  - build

lint-backend:
  stage: lint
  image: python:3.11-slim
  script:
    - pip install ruff
    - ruff check backend/

lint-frontend:
  stage: lint
  image: node:23
  script:
    - cd frontend
    - npm install
    - npm install -g eslint
    - eslint .

build-job:
  stage: build
  image: node:23
  variables:
    VITE_BACKEND_URL: "http://134.209.19.90:3000/"
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
    - build/