version: '3.8'

services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    networks:
      - my-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=carbon_foot
      - POSTGRES_PASSWORD=carbon_foot
      - POSTGRES_DB=carbon_foot_dev
    networks:
      - my-network
    ports:
      - "5432:5432"

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
    - "3000:3000"
    networks:
      - my-network

volumes:
  postgres_data:

networks:
  my-network: