services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    networks:
      - my-network
    depends_on:
      - db

  db:
    image: postgres:17
    build: .
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=carbon_foot
      - POSTGRES_PASSWORD=carbon_foot
      - POSTGRES_DB=carbon_foot_dev
    networks:
      - my-network
    ports:
      - "5432:5432"

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      WATCHPACK_POLLING: "true"
    env_file:
      - ./.env.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - web

volumes:
  postgres_data:

networks:
  my-network:
