version: '3.8'

services:
  web:
    build: 
      context: ./backend
      dockerfile: Dockerfile_prod
    command: gunicorn carbonfoot.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      WATCHPACK_POLLING: "true"
    env_file:
      - ./.env.prod
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
    - "3000:3000"
