



GET /api2/whoami/ HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: zh-CN,zh;q=0.9,ja;q=0.8
Connection: keep-alive
Cookie: csrftoken=gWMDBRyoeE65gmJWyoypEGGNGfpwlzHS; csrftoken=duL60Olpr0JgEVww7JrvcbpZRId1K6kt; sessionid=73gtmdh49uj6wjxlfilumixp6gv94x7q
Host: localhost:8000
Origin: http://localhost:3000
Referer: http://localhost:3000/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"

### test get id

GET http://localhost:8000/api2/test/ HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: zh-CN,zh;q=0.9,ja;q=0.8
Connection: keep-alive
Cookie: csrftoken=gWMDBRyoeE65gmJWyoypEGGNGfpwlzHS; csrftoken=duL60Olpr0JgEVww7JrvcbpZRId1K6kt; sessionid=73gtmdh49uj6wjxlfilumixp6gv94x7q
Host: localhost:8000
Origin: http://localhost:3000
Referer: http://localhost:3000/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"






### test  get-csrf
GET http://localhost:8000/api2/get-csrf/



### test report
POST http://localhost:8000/api2/Report/
Content-Type: application/json
Cookie: sessionid=p90kgzgo4ia8nr35yww8f36b8v2upxjb; csrftoken=gWMDBRyoeE65gmJWyoypEGGNGfpwlzHS
X-CSRFToken: gWMDBRyoeE65gmJWyoypEGGNGfpwlzHS

{
  "utilities": {
    "FTE-staff": "10",
    "FTE-members": "20",
    "academic-laboratory-area": "100",
    "academic-office-area": "200",
    "admin-office-area": "300",
    "admin-space-area": "150",
    "medical-laboratory-area": "250",
    "engineering-laboratory-area": "350",
    "physical-laboratory-area": "400"
  },
  "travel": {
    "air-eco-short": "1000",
    "air-business-short": "500",
    "air-eco-long": "800",
    "air-business-long": "300",
    "land-car": "1200",
    "land-bus": "400"
  },
  "waste": {
    "mixed-recycle": "2",
    "general-waste": "3",
    "clinical-waste": "1.5",
    "chemical-waste": "0.5",
    "bio-waste": "0.8"
  },
  "procurement": {
    "CA": 100,
    "WB": 200,
    "PA": 50,
    "AF": 150,
    "TA": 120,
    "AB": 1,
    "C": 100
  }
}

### test submit
POST http://localhost:8000/api2/Submit/
Content-Type: application/json
Cookie: csrftoken=gWMDBRyoeE65gmJWyoypEGGNGfpwlzHS; csrftoken=duL60Olpr0JgEVww7JrvcbpZRId1K6kt; sessionid=73gtmdh49uj6wjxlfilumixp6gv94x7q
X-CSRFToken: duL60Olpr0JgEVww7JrvcbpZRId1K6kt

{
  "utilities": {
    "FTE-staff": "10",
    "FTE-members": "20",
    "academic-laboratory-area": "100",
    "academic-office-area": "200",
    "admin-office-area": "300",
    "admin-space-area": "150",
    "medical-laboratory-area": "250",
    "engineering-laboratory-area": "350",
    "physical-laboratory-area": "400"
  },
  "travel": {
    "air-eco-short": "1000",
    "air-business-short": "500",
    "air-eco-long": "800",
    "air-business-long": "300",
    "land-car": "1200",
    "land-bus": "400"
  },
  "waste": {
    "mixed-recycle": "2",
    "general-waste": "3",
    "clinical-waste": "1.5",
    "chemical-waste": "0.5",
    "bio-waste": "0.8"
  },
  "procurement": {
    "CA": 100,
    "WB": 200,
    "PA": 50,
    "AF": 150,
    "TA": 120,
    "AB": 1,
    "C": 100
  }
}
