



GET /api2/session/ HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: zh-CN,zh;q=0.9,ja;q=0.8
Connection: keep-alive
Cookie: sessionid=w49ldbz6z15wdad7c10lck0q36uf19l3; csrftoken=O1jCsJa6tlABfWlIecZnF48WoB9M7hqV
Host: localhost:8000
Origin: http://localhost:3000
Referer: http://localhost:3000/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"

### test get id

GET http://localhost:8000/api2/test/ HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: zh-CN,zh;q=0.9,ja;q=0.8
Connection: keep-alive
Cookie: csrftoken=bGmHThfLC9SUHvPdxqRwUbAB6PtyA0zN; sessionid=vjgwk3xhkph48xd80e30ryhbs77500jr
Host: localhost:8000
Origin: http://localhost:3000
Referer: http://localhost:3000/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
sec-ch-ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"






### test  get-csrf
GET http://localhost:8000/api2/get-csrf/



### test report
POST http://localhost:8000/api2/report/
Content-Type: application/json
Cookie: csrftoken=dnUC3jC8z3JhBzeFSQBn9bHP9h2ZTud0; sessionid=jblb5ri17cnbi7yglf3n9eecx99lxcrn
X-CSRFToken: dnUC3jC8z3JhBzeFSQBn9bHP9h2ZTud0

{
  "utilities": {
    "FTE-staff": "10",
    "FTE-members": "20",
    "Academic Laboratory": "100",
    "Academic Office": "200",
    "Admin Office": "300",
    "Office/Admin Space": "150",
    "Medical/Life Sciences Laboratory": "250",
    "Engineering Laboratory": "350",
    "Physical Sciences Laboratory": "400"
  },
  "travel": {
    "air-eco-short-UK": "1000",
    "air-business-short-UK": "500",
    "air-eco-long-UK": "800",
    "air-business-long-UK": "300",
    "land-car": "1200",
    "land-local-bus": "400"
  },
  "waste": {
    "mixed-recycle": "2",
    "general-waste": "3",
    "clinical-waste": "1.5",
    "chemical-waste": "0.5",
    "bio-waste": "0.8"
  },
  "procurement": {
    "CA": 100,
    "WB": 200,
    "PA": 50,
    "AF": 150,
    "TA": 120,
    "AB": 1,
    "C": 100
  }
}

### test submit
POST http://localhost:8000/api2/submit/
Content-Type: application/json
Cookie: csrftoken=dnUC3jC8z3JhBzeFSQBn9bHP9h2ZTud0; sessionid=jblb5ri17cnbi7yglf3n9eecx99lxcrn
X-CSRFToken: dnUC3jC8z3JhBzeFSQBn9bHP9h2ZTud0

{
  "utilities": {
    "FTE-staff": "10",
    "FTE-members": "20",
    "Academic Laboratory": "100",
    "Academic Office": "200",
    "Admin Office": "300",
    "Office/Admin Space": "150",
    "Medical/Life Sciences Laboratory": "250",
    "Engineering Laboratory": "350",
    "Physical Sciences Laboratory": "400"
  },
  "travel": {
    "air-eco-short-UK": "1000",
    "air-business-short-UK": "500",
    "air-eco-long-UK": "800",
    "air-business-long-UK": "300",
    "land-car": "1200",
    "land-local-bus": "400"
  },
  "waste": {
    "mixed-recycle": "2",
    "general-waste": "3",
    "clinical-waste": "1.5",
    "chemical-waste": "0.5",
    "bio-waste": "0.8"
  },
  "procurement": {
    "CA": 100,
    "WB": 200,
    "PA": 50,
    "AF": 150,
    "TA": 120,
    "AB": 1,
    "C": 100
  }
}

### test getresult
POST http://localhost:8000/api2/dashboard-show-user-result-data/
Content-Type: application/json
Cookie: csrftoken=CteR7VevcTLfsoEB3R8ndre663DtY8JF; sessionid=y8vcav9lpr2a71qehwywukjzkxftx275
X-CSRFToken: CteR7VevcTLfsoEB3R8ndre663DtY8JF

### 发送 POST 请求测试 get_all_report_data API
POST http://localhost:8000/api2/get-all-report-data/
Content-Type: application/json
Cookie: csrftoken=dnUC3jC8z3JhBzeFSQBn9bHP9h2ZTud0; sessionid=jblb5ri17cnbi7yglf3n9eecx99lxcrn
X-CSRFToken: dnUC3jC8z3JhBzeFSQBn9bHP9h2ZTud0

{
  "report_id": 1
}


### test update_carbon_impact
POST http://localhost:8000/api2/update-carbon-impact/
Content-Type: application/json
Cookie: csrftoken=dnUC3jC8z3JhBzeFSQBn9bHP9h2ZTud0; sessionid=jblb5ri17cnbi7yglf3n9eecx99lxcrn
X-CSRFToken: dnUC3jC8z3JhBzeFSQBn9bHP9h2ZTud0

{
    "category": "Bread",
    "carbon_impact": 2.99398372857928759
}

### test get_all_carbon_impact
GET http://localhost:8000/api2/get-all-carbon-impact/
Content-Type: application/json
Cookie: csrftoken=J1PwLcPb5S42lvqJ6mUBgNtXGKsa5I8T; sessionid=njhv0qeoibnmtpj242b1nk400qwrrckd
X-CSRFToken: J1PwLcPb5S42lvqJ6mUBgNtXGKsa5I8T


### test submit-adminrequest
POST http://localhost:8000/api2/submit-adminrequest/
Content-Type: application/json
Cookie: csrftoken=E8E0tSEPlUwg6COlHsTJMX4maKLL34Ul; sessionid=bqz91luvpj3ma9oe7u5mzxm5j5g3z639
X-CSRFToken: E8E0tSEPlUwg6COlHsTJMX4maKLL34Ul

{
    "requested_role": "researcher",
    "reason": "I need researcher permissions to researcher human."
}

### test admin_request_list
GET http://localhost:8000/api2/admin-request-list/
Content-Type: application/json
Cookie: csrftoken=CteR7VevcTLfsoEB3R8ndre663DtY8JF; sessionid=y8vcav9lpr2a71qehwywukjzkxftx275
X-CSRFToken: CteR7VevcTLfsoEB3R8ndre663DtY8JF

### test user_request_list
GET http://localhost:8000/api2/user-request-status/
Content-Type: application/json
Cookie: csrftoken=CteR7VevcTLfsoEB3R8ndre663DtY8JF; sessionid=y8vcav9lpr2a71qehwywukjzkxftx275
X-CSRFToken: CteR7VevcTLfsoEB3R8ndre663DtY8JF

### test submit-adminrequest
POST http://localhost:8000/api2/approve-or-reject-request/
Content-Type: application/json
Cookie: csrftoken=CteR7VevcTLfsoEB3R8ndre663DtY8JF; sessionid=y8vcav9lpr2a71qehwywukjzkxftx275
X-CSRFToken: CteR7VevcTLfsoEB3R8ndre663DtY8JF

{
    "user_id": 2,
    "state": "Approved"
}

### test save draft
POST http://localhost:8000/api2/store-unsubmitted-reports-backend/
Content-Type: application/json
Cookie: csrftoken=CteR7VevcTLfsoEB3R8ndre663DtY8JF; sessionid=y8vcav9lpr2a71qehwywukjzkxftx275
X-CSRFToken: CteR7VevcTLfsoEB3R8ndre663DtY8JF

{
  "utilities": {
    "FTE-staff": "10",
    "FTE-members": "20"
  },
  "travel": {
    "air-eco-short-UK": "1000"
  }
}

### test get draft
GET http://localhost:8000/api2/retrieve-and-delete-temp-report/
Content-Type: application/json
Cookie: csrftoken=CteR7VevcTLfsoEB3R8ndre663DtY8JF; sessionid=y8vcav9lpr2a71qehwywukjzkxftx275
X-CSRFToken: CteR7VevcTLfsoEB3R8ndre663DtY8JF